apiVersion: v1
kind: Service
metadata:
  name: cv-analyzer-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: cv-analyzer-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

